name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: dhf0820
      IMAGE_NAME: core_amd64
      BINARY_NAME: core
      VERSION: latest
      GOPRIVATE: github.com/dhf0820/*
      GIT_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Configure Git for private module access
        run: |
          git config --global url."https://${GIT_AUTH_TOKEN}@github.com/".insteadOf "https://github.com/"
        env:
          GIT_AUTH_TOKEN: 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


      - name: Install Protobuf and Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          #go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.24.2
          #go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0
          #echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Generate Protobuf
        run: make api

      - name: Generate Certs
        run: make cert

      - name: Tidy and Build
        run: |
          make tidy
          make build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          make release
